# Permalinks
permalink:           pretty

# Setup
title:               Matt Johnson
tagline:             Your friendly neighborhood data person
url:                 http://www.onlymattjohnson.com
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Matt Johnson
  url:               https://twitter.com/monlymattjohnson
  email:             mjohn23@gmail.com

# Gems
gems:
  - jekyll-paginate

# Google Analytics
analytics_id: UA-220177431-1